// Auto-generated by apps/api/scripts/catalog-guard.mjs. Do not edit manually.

export const CROSSFIN_API_VERSION = "1.18.0"

export const CROSSFIN_PLAYGROUND_ENDPOINTS: { path: string; label: string }[] = [
  {
    "path": "/api/health",
    "label": "[Free] Health Check"
  },
  {
    "path": "/api/registry/stats",
    "label": "[Free] Registry Stats"
  },
  {
    "path": "/api/registry/categories",
    "label": "[Free] Categories"
  },
  {
    "path": "/api/arbitrage/demo",
    "label": "[Free] Route Spread Preview"
  },
  {
    "path": "/api/analytics/overview",
    "label": "[Free] Analytics Overview"
  },
  {
    "path": "/api/stats",
    "label": "[Free] Agent Stats"
  },
  {
    "path": "/api/openapi.json",
    "label": "[Free] OpenAPI Spec"
  },
  {
    "path": "/api/route/exchanges",
    "label": "[Free] Route Exchanges"
  },
  {
    "path": "/api/route/fees",
    "label": "[Free] Route Fees"
  },
  {
    "path": "/api/route/status",
    "label": "[Free] Route Status"
  },
  {
    "path": "/api/acp/status",
    "label": "[Free] ACP Status"
  },
  {
    "path": "/api/docs/guide",
    "label": "[Free] Agent Guide"
  },
  {
    "path": "/api/registry/search",
    "label": "[Free] Registry Search"
  },
  {
    "path": "/api/routing/optimal",
    "label": "[Free] Optimal Route"
  },
  {
    "path": "/api/route/pairs",
    "label": "[Free] Exchange Prices"
  },
  {
    "path": "/api/premium/report",
    "label": "[Free (Open Beta)] Premium Report (normally $0.001)"
  },
  {
    "path": "/api/premium/enterprise",
    "label": "[Free (Open Beta)] Enterprise Receipt (normally $20.00)"
  },
  {
    "path": "/api/premium/arbitrage/kimchi",
    "label": "[Free (Open Beta)] Route Spread (normally $0.05)"
  },
  {
    "path": "/api/premium/arbitrage/kimchi/history?hours=24",
    "label": "[Free (Open Beta)] Route Spread History (normally $0.05)"
  },
  {
    "path": "/api/premium/arbitrage/opportunities",
    "label": "[Free (Open Beta)] Arbitrage Opportunities (normally $0.10)"
  },
  {
    "path": "/api/premium/bithumb/orderbook?pair=BTC",
    "label": "[Free (Open Beta)] Bithumb Orderbook (normally $0.02)"
  },
  {
    "path": "/api/premium/bithumb/volume-analysis",
    "label": "[Free (Open Beta)] Bithumb Volume Analysis (normally $0.03)"
  },
  {
    "path": "/api/premium/market/korea",
    "label": "[Free (Open Beta)] Korea Market Sentiment (normally $0.03)"
  },
  {
    "path": "/api/premium/market/fx/usdkrw",
    "label": "[Free (Open Beta)] USD/KRW (FX) (normally $0.01)"
  },
  {
    "path": "/api/premium/market/upbit/ticker?market=KRW-BTC",
    "label": "[Free (Open Beta)] Upbit Ticker (normally $0.02)"
  },
  {
    "path": "/api/premium/market/upbit/orderbook?market=KRW-BTC",
    "label": "[Free (Open Beta)] Upbit Orderbook (normally $0.02)"
  },
  {
    "path": "/api/premium/market/upbit/signals",
    "label": "[Free (Open Beta)] Upbit Signals (normally $0.05)"
  },
  {
    "path": "/api/premium/market/coinone/ticker?currency=BTC",
    "label": "[Free (Open Beta)] Coinone Ticker (normally $0.02)"
  },
  {
    "path": "/api/premium/market/cross-exchange",
    "label": "[Free (Open Beta)] Cross-Exchange Decision (normally $0.08)"
  },
  {
    "path": "/api/premium/crypto/korea/5exchange?coin=BTC",
    "label": "[Free (Open Beta)] Korea 5-Exchange Compare (normally $0.08)"
  },
  {
    "path": "/api/premium/crypto/korea/exchange-status",
    "label": "[Free (Open Beta)] Korea Exchange Status (normally $0.03)"
  },
  {
    "path": "/api/premium/crypto/korea/fx-rate",
    "label": "[Free (Open Beta)] Korea FX Rate (CRIX) (normally $0.01)"
  },
  {
    "path": "/api/premium/crypto/korea/upbit-candles?coin=BTC&type=days&count=30",
    "label": "[Free (Open Beta)] Upbit Candles (normally $0.02)"
  },
  {
    "path": "/api/premium/news/korea/headlines",
    "label": "[Free (Open Beta)] Korea Headlines (normally $0.03)"
  },
  {
    "path": "/api/premium/morning/brief",
    "label": "[Free (Open Beta)] Morning Brief (normally $0.20)"
  },
  {
    "path": "/api/premium/crypto/snapshot",
    "label": "[Free (Open Beta)] Crypto Snapshot (normally $0.15)"
  },
  {
    "path": "/api/premium/kimchi/stats",
    "label": "[Free (Open Beta)] Route Spread Stats (normally $0.15)"
  },
  {
    "path": "/api/premium/route/find?from=bithumb:KRW&to=binance:USDC&amount=1000000&strategy=cheapest",
    "label": "[Free (Open Beta)] Route Finder (normally $0.10)"
  }
]
