// Auto-generated by apps/api/scripts/catalog-guard.mjs. Do not edit manually.

export const CROSSFIN_API_VERSION = "1.8.7"

export const CROSSFIN_PLAYGROUND_ENDPOINTS: { path: string; label: string }[] = [
  {
    "path": "/api/health",
    "label": "[Free] Health Check"
  },
  {
    "path": "/api/registry/stats",
    "label": "[Free] Registry Stats"
  },
  {
    "path": "/api/registry/categories",
    "label": "[Free] Categories"
  },
  {
    "path": "/api/arbitrage/demo",
    "label": "[Free] Route Spread Preview"
  },
  {
    "path": "/api/analytics/overview",
    "label": "[Free] Analytics Overview"
  },
  {
    "path": "/api/openapi.json",
    "label": "[Free] OpenAPI Spec"
  },
  {
    "path": "/api/route/exchanges",
    "label": "[Free] Route Exchanges"
  },
  {
    "path": "/api/route/fees",
    "label": "[Free] Route Fees"
  },
  {
    "path": "/api/route/status",
    "label": "[Free] Route Status"
  },
  {
    "path": "/api/acp/status",
    "label": "[Free] ACP Status"
  },
  {
    "path": "/api/premium/report",
    "label": "[Paid] Premium Report ($0.001)"
  },
  {
    "path": "/api/premium/enterprise",
    "label": "[Paid] Enterprise Receipt ($20.00)"
  },
  {
    "path": "/api/premium/arbitrage/kimchi",
    "label": "[Paid] Route Spread ($0.05)"
  },
  {
    "path": "/api/premium/arbitrage/kimchi/history?hours=24",
    "label": "[Paid] Route Spread History ($0.05)"
  },
  {
    "path": "/api/premium/arbitrage/opportunities",
    "label": "[Paid] Arbitrage Opportunities ($0.10)"
  },
  {
    "path": "/api/premium/bithumb/orderbook?pair=BTC",
    "label": "[Paid] Bithumb Orderbook ($0.02)"
  },
  {
    "path": "/api/premium/bithumb/volume-analysis",
    "label": "[Paid] Bithumb Volume Analysis ($0.03)"
  },
  {
    "path": "/api/premium/market/korea",
    "label": "[Paid] Korea Market Sentiment ($0.03)"
  },
  {
    "path": "/api/premium/market/fx/usdkrw",
    "label": "[Paid] USD/KRW (FX) ($0.01)"
  },
  {
    "path": "/api/premium/market/upbit/ticker?market=KRW-BTC",
    "label": "[Paid] Upbit Ticker ($0.02)"
  },
  {
    "path": "/api/premium/market/upbit/orderbook?market=KRW-BTC",
    "label": "[Paid] Upbit Orderbook ($0.02)"
  },
  {
    "path": "/api/premium/market/upbit/signals",
    "label": "[Paid] Upbit Signals ($0.05)"
  },
  {
    "path": "/api/premium/market/coinone/ticker?currency=BTC",
    "label": "[Paid] Coinone Ticker ($0.02)"
  },
  {
    "path": "/api/premium/market/cross-exchange",
    "label": "[Paid] Cross-Exchange Decision ($0.08)"
  },
  {
    "path": "/api/premium/market/korea/indices",
    "label": "[Paid] Korea Indices ($0.03)"
  },
  {
    "path": "/api/premium/market/korea/indices/history?index=KOSPI&days=20",
    "label": "[Paid] Korea Indices History ($0.05)"
  },
  {
    "path": "/api/premium/market/korea/stocks/momentum?market=KOSPI",
    "label": "[Paid] Korea Stocks Momentum ($0.05)"
  },
  {
    "path": "/api/premium/market/korea/investor-flow?stock=005930",
    "label": "[Paid] Korea Investor Flow ($0.05)"
  },
  {
    "path": "/api/premium/market/korea/index-flow?index=KOSPI",
    "label": "[Paid] Korea Index Flow ($0.03)"
  },
  {
    "path": "/api/premium/crypto/korea/5exchange?coin=BTC",
    "label": "[Paid] Korea 4-Exchange Compare ($0.08)"
  },
  {
    "path": "/api/premium/crypto/korea/exchange-status",
    "label": "[Paid] Korea Exchange Status ($0.03)"
  },
  {
    "path": "/api/premium/market/korea/stock-detail?stock=005930",
    "label": "[Paid] Korea Stock Detail ($0.05)"
  },
  {
    "path": "/api/premium/market/korea/stock-news?stock=005930",
    "label": "[Paid] Korea Stock News ($0.03)"
  },
  {
    "path": "/api/premium/market/korea/themes",
    "label": "[Paid] Korea Themes ($0.05)"
  },
  {
    "path": "/api/premium/market/korea/disclosure?stock=005930",
    "label": "[Paid] Korea Disclosure ($0.03)"
  },
  {
    "path": "/api/premium/crypto/korea/fx-rate",
    "label": "[Paid] Korea FX Rate (CRIX) ($0.01)"
  },
  {
    "path": "/api/premium/market/korea/etf",
    "label": "[Paid] Korea ETF ($0.03)"
  },
  {
    "path": "/api/premium/crypto/korea/upbit-candles?coin=BTC&type=days&count=30",
    "label": "[Paid] Upbit Candles ($0.02)"
  },
  {
    "path": "/api/premium/market/global/indices-chart?index=.DJI&period=month",
    "label": "[Paid] Global Indices Chart ($0.02)"
  },
  {
    "path": "/api/premium/news/korea/headlines",
    "label": "[Paid] Korea Headlines ($0.03)"
  },
  {
    "path": "/api/premium/morning/brief",
    "label": "[Paid] Morning Brief ($0.20)"
  },
  {
    "path": "/api/premium/crypto/snapshot",
    "label": "[Paid] Crypto Snapshot ($0.15)"
  },
  {
    "path": "/api/premium/kimchi/stats",
    "label": "[Paid] Route Spread Stats ($0.15)"
  },
  {
    "path": "/api/premium/market/korea/stock-brief?stock=005930",
    "label": "[Paid] Stock Brief ($0.10)"
  },
  {
    "path": "/api/premium/route/find?from=bithumb:KRW&to=binance:USDC&amount=1000000&strategy=cheapest",
    "label": "[Paid] Route Finder ($0.10)"
  }
]
